emr:
  aws_access_key: AKIAIT733CWAJCYK5XVQ
  aws_secret_access_key: 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
  region_name: us-east-1
  cluster_name: Spark_Offerdata2
  instance_count: 3
  master_instance_type: m3.xlarge
  slave_instance_type: m4.large
  key_name: EMR-keypair
  subnet_id: subnet-2ced5600
  log_uri: s3://aws-logs-837749433225-us-east-1/elasticmapreduce
  software_version: emr-5.8.0
  script_bucket_name: emr-bootstrap1-bucket